# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Aug 11 19:07:47 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 450)
        MainWindow.setMinimumSize(QtCore.QSize(800, 450))
        MainWindow.setMaximumSize(QtCore.QSize(800, 450))
        MainWindow.setBaseSize(QtCore.QSize(800, 450))
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.progressBar_RPM = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_RPM.setGeometry(QtCore.QRect(2, 2, 796, 81))
        self.progressBar_RPM.setMaximumSize(QtCore.QSize(800, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.progressBar_RPM.setFont(font)
        self.progressBar_RPM.setAutoFillBackground(False)
        self.progressBar_RPM.setStyleSheet(_fromUtf8(""))
        self.progressBar_RPM.setMaximum(6000)
        self.progressBar_RPM.setProperty("value", 3878)
        self.progressBar_RPM.setTextVisible(True)
        self.progressBar_RPM.setObjectName(_fromUtf8("progressBar_RPM"))
        self.lcdNumber_Vbat = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Vbat.setGeometry(QtCore.QRect(70, 210, 131, 81))
        self.lcdNumber_Vbat.setNumDigits(3)
        self.lcdNumber_Vbat.setProperty("value", 112.0)
        self.lcdNumber_Vbat.setObjectName(_fromUtf8("lcdNumber_Vbat"))
        self.lcdNumber_Imax = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Imax.setGeometry(QtCore.QRect(70, 90, 131, 81))
        self.lcdNumber_Imax.setNumDigits(3)
        self.lcdNumber_Imax.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_Imax.setProperty("value", 43.0)
        self.lcdNumber_Imax.setObjectName(_fromUtf8("lcdNumber_Imax"))
        self.progressBar_SOC = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_SOC.setGeometry(QtCore.QRect(2, 90, 61, 271))
        self.progressBar_SOC.setProperty("value", 78)
        self.progressBar_SOC.setTextVisible(False)
        self.progressBar_SOC.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_SOC.setInvertedAppearance(False)
        self.progressBar_SOC.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_SOC.setObjectName(_fromUtf8("progressBar_SOC"))
        self.progressBar_Tbat = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_Tbat.setGeometry(QtCore.QRect(595, 90, 61, 271))
        self.progressBar_Tbat.setMinimum(10)
        self.progressBar_Tbat.setMaximum(150)
        self.progressBar_Tbat.setProperty("value", 67)
        self.progressBar_Tbat.setTextVisible(False)
        self.progressBar_Tbat.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_Tbat.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar_Tbat.setObjectName(_fromUtf8("progressBar_Tbat"))
        self.progressBar_Tdriver = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_Tdriver.setGeometry(QtCore.QRect(665, 90, 61, 271))
        self.progressBar_Tdriver.setMinimum(10)
        self.progressBar_Tdriver.setMaximum(85)
        self.progressBar_Tdriver.setProperty("value", 68)
        self.progressBar_Tdriver.setTextVisible(False)
        self.progressBar_Tdriver.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_Tdriver.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_Tdriver.setObjectName(_fromUtf8("progressBar_Tdriver"))
        self.progressBar_Tengine = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_Tengine.setGeometry(QtCore.QRect(735, 90, 61, 271))
        self.progressBar_Tengine.setMinimum(10)
        self.progressBar_Tengine.setMaximum(150)
        self.progressBar_Tengine.setProperty("value", 47)
        self.progressBar_Tengine.setTextVisible(False)
        self.progressBar_Tengine.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_Tengine.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar_Tengine.setObjectName(_fromUtf8("progressBar_Tengine"))
        self.lcdNumber_SOC = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_SOC.setGeometry(QtCore.QRect(2, 400, 61, 41))
        self.lcdNumber_SOC.setSmallDecimalPoint(False)
        self.lcdNumber_SOC.setDigitCount(3)
        self.lcdNumber_SOC.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_SOC.setProperty("value", 78.0)
        self.lcdNumber_SOC.setObjectName(_fromUtf8("lcdNumber_SOC"))
        self.lcdNumber_Tbat = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Tbat.setGeometry(QtCore.QRect(595, 400, 61, 41))
        self.lcdNumber_Tbat.setSmallDecimalPoint(True)
        self.lcdNumber_Tbat.setNumDigits(3)
        self.lcdNumber_Tbat.setDigitCount(3)
        self.lcdNumber_Tbat.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Tbat.setProperty("value", 67.0)
        self.lcdNumber_Tbat.setObjectName(_fromUtf8("lcdNumber_Tbat"))
        self.lcdNumber_Tdriver = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Tdriver.setGeometry(QtCore.QRect(665, 400, 61, 41))
        self.lcdNumber_Tdriver.setSmallDecimalPoint(True)
        self.lcdNumber_Tdriver.setNumDigits(3)
        self.lcdNumber_Tdriver.setDigitCount(3)
        self.lcdNumber_Tdriver.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Tdriver.setProperty("value", 85.0)
        self.lcdNumber_Tdriver.setObjectName(_fromUtf8("lcdNumber_Tdriver"))
        self.lcdNumber_Tengine = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Tengine.setGeometry(QtCore.QRect(735, 400, 61, 41))
        self.lcdNumber_Tengine.setSmallDecimalPoint(True)
        self.lcdNumber_Tengine.setDigitCount(3)
        self.lcdNumber_Tengine.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Tengine.setProperty("value", 47.0)
        self.lcdNumber_Tengine.setObjectName(_fromUtf8("lcdNumber_Tengine"))
        self.lcdNumber_Tmaxcell = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Tmaxcell.setGeometry(QtCore.QRect(460, 400, 91, 41))
        self.lcdNumber_Tmaxcell.setSmallDecimalPoint(True)
        self.lcdNumber_Tmaxcell.setNumDigits(4)
        self.lcdNumber_Tmaxcell.setDigitCount(4)
        self.lcdNumber_Tmaxcell.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Tmaxcell.setProperty("value", 113.65)
        self.lcdNumber_Tmaxcell.setObjectName(_fromUtf8("lcdNumber_Tmaxcell"))
        self.lcdNumber_Tmincell = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Tmincell.setGeometry(QtCore.QRect(340, 400, 91, 41))
        self.lcdNumber_Tmincell.setSmallDecimalPoint(True)
        self.lcdNumber_Tmincell.setNumDigits(4)
        self.lcdNumber_Tmincell.setDigitCount(4)
        self.lcdNumber_Tmincell.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Tmincell.setProperty("value", 104.0)
        self.lcdNumber_Tmincell.setProperty("intValue", 104)
        self.lcdNumber_Tmincell.setObjectName(_fromUtf8("lcdNumber_Tmincell"))
        self.lcdNumber_Vmaxcell = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Vmaxcell.setGeometry(QtCore.QRect(210, 400, 91, 41))
        self.lcdNumber_Vmaxcell.setSmallDecimalPoint(True)
        self.lcdNumber_Vmaxcell.setNumDigits(4)
        self.lcdNumber_Vmaxcell.setDigitCount(4)
        self.lcdNumber_Vmaxcell.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Vmaxcell.setProperty("value", 113.65)
        self.lcdNumber_Vmaxcell.setObjectName(_fromUtf8("lcdNumber_Vmaxcell"))
        self.lcdNumber_Vmincell = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_Vmincell.setGeometry(QtCore.QRect(92, 400, 91, 41))
        self.lcdNumber_Vmincell.setSmallDecimalPoint(True)
        self.lcdNumber_Vmincell.setNumDigits(4)
        self.lcdNumber_Vmincell.setDigitCount(4)
        self.lcdNumber_Vmincell.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_Vmincell.setProperty("value", 104.0)
        self.lcdNumber_Vmincell.setProperty("intValue", 104)
        self.lcdNumber_Vmincell.setObjectName(_fromUtf8("lcdNumber_Vmincell"))
        self.label_SOC = QtGui.QLabel(self.centralwidget)
        self.label_SOC.setGeometry(QtCore.QRect(2, 360, 61, 41))
        self.label_SOC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SOC.setObjectName(_fromUtf8("label_SOC"))
        self.label_Tengine = QtGui.QLabel(self.centralwidget)
        self.label_Tengine.setGeometry(QtCore.QRect(735, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Tengine.setFont(font)
        self.label_Tengine.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tengine.setObjectName(_fromUtf8("label_Tengine"))
        self.label_Tdriver = QtGui.QLabel(self.centralwidget)
        self.label_Tdriver.setGeometry(QtCore.QRect(665, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Tdriver.setFont(font)
        self.label_Tdriver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tdriver.setObjectName(_fromUtf8("label_Tdriver"))
        self.label_Tbat = QtGui.QLabel(self.centralwidget)
        self.label_Tbat.setGeometry(QtCore.QRect(595, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Tbat.setFont(font)
        self.label_Tbat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tbat.setObjectName(_fromUtf8("label_Tbat"))
        self.label_Vmincell = QtGui.QLabel(self.centralwidget)
        self.label_Vmincell.setGeometry(QtCore.QRect(92, 360, 91, 41))
        self.label_Vmincell.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vmincell.setObjectName(_fromUtf8("label_Vmincell"))
        self.label_Vmaxcell = QtGui.QLabel(self.centralwidget)
        self.label_Vmaxcell.setGeometry(QtCore.QRect(212, 360, 91, 41))
        self.label_Vmaxcell.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vmaxcell.setObjectName(_fromUtf8("label_Vmaxcell"))
        self.label_Tmaxcell = QtGui.QLabel(self.centralwidget)
        self.label_Tmaxcell.setGeometry(QtCore.QRect(460, 360, 91, 41))
        self.label_Tmaxcell.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tmaxcell.setObjectName(_fromUtf8("label_Tmaxcell"))
        self.label_Tmincell = QtGui.QLabel(self.centralwidget)
        self.label_Tmincell.setGeometry(QtCore.QRect(340, 360, 91, 41))
        self.label_Tmincell.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tmincell.setObjectName(_fromUtf8("label_Tmincell"))
        self.label_Vbat = QtGui.QLabel(self.centralwidget)
        self.label_Vbat.setGeometry(QtCore.QRect(200, 250, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_Vbat.setFont(font)
        self.label_Vbat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vbat.setObjectName(_fromUtf8("label_Vbat"))
        self.label_Imax = QtGui.QLabel(self.centralwidget)
        self.label_Imax.setGeometry(QtCore.QRect(200, 130, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_Imax.setFont(font)
        self.label_Imax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Imax.setObjectName(_fromUtf8("label_Imax"))
        self.lcdNumber_KMH = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_KMH.setGeometry(QtCore.QRect(250, 90, 321, 201))
        self.lcdNumber_KMH.setNumDigits(3)
        self.lcdNumber_KMH.setProperty("value", 112.0)
        self.lcdNumber_KMH.setObjectName(_fromUtf8("lcdNumber_KMH"))
        self.label_KMH = QtGui.QLabel(self.centralwidget)
        self.label_KMH.setGeometry(QtCore.QRect(460, 290, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_KMH.setFont(font)
        self.label_KMH.setAlignment(QtCore.Qt.AlignCenter)
        self.label_KMH.setObjectName(_fromUtf8("label_KMH"))
        self.label_SOC_units = QtGui.QLabel(self.centralwidget)
        self.label_SOC_units.setGeometry(QtCore.QRect(60, 410, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_SOC_units.setFont(font)
        self.label_SOC_units.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SOC_units.setObjectName(_fromUtf8("label_SOC_units"))
        self.label_Vmincell_units = QtGui.QLabel(self.centralwidget)
        self.label_Vmincell_units.setGeometry(QtCore.QRect(180, 410, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Vmincell_units.setFont(font)
        self.label_Vmincell_units.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vmincell_units.setObjectName(_fromUtf8("label_Vmincell_units"))
        self.label_Vmaxcell_units = QtGui.QLabel(self.centralwidget)
        self.label_Vmaxcell_units.setGeometry(QtCore.QRect(300, 410, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Vmaxcell_units.setFont(font)
        self.label_Vmaxcell_units.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Vmaxcell_units.setObjectName(_fromUtf8("label_Vmaxcell_units"))
        self.label_Tmincell_units = QtGui.QLabel(self.centralwidget)
        self.label_Tmincell_units.setGeometry(QtCore.QRect(430, 410, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Tmincell_units.setFont(font)
        self.label_Tmincell_units.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tmincell_units.setObjectName(_fromUtf8("label_Tmincell_units"))
        self.label_Tmaxcell_units = QtGui.QLabel(self.centralwidget)
        self.label_Tmaxcell_units.setGeometry(QtCore.QRect(550, 410, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Tmaxcell_units.setFont(font)
        self.label_Tmaxcell_units.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Tmaxcell_units.setObjectName(_fromUtf8("label_Tmaxcell_units"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.progressBar_RPM.setFormat(_translate("MainWindow", "%v rpm", None))
        self.label_SOC.setText(_translate("MainWindow", "SOC", None))
        self.label_Tengine.setText(_translate("MainWindow", "T ENG", None))
        self.label_Tdriver.setText(_translate("MainWindow", "T DRV", None))
        self.label_Tbat.setText(_translate("MainWindow", "T BAT", None))
        self.label_Vmincell.setText(_translate("MainWindow", "V MIN CELL", None))
        self.label_Vmaxcell.setText(_translate("MainWindow", "V MAX CELL", None))
        self.label_Tmaxcell.setText(_translate("MainWindow", "T MAX CELL", None))
        self.label_Tmincell.setText(_translate("MainWindow", "T MIN CELL", None))
        self.label_Vbat.setText(_translate("MainWindow", "V", None))
        self.label_Imax.setText(_translate("MainWindow", "A", None))
        self.label_KMH.setText(_translate("MainWindow", "km/h", None))
        self.label_SOC_units.setText(_translate("MainWindow", "%", None))
        self.label_Vmincell_units.setText(_translate("MainWindow", "V", None))
        self.label_Vmaxcell_units.setText(_translate("MainWindow", "V", None))
        self.label_Tmincell_units.setText(_translate("MainWindow", "°C", None))
        self.label_Tmaxcell_units.setText(_translate("MainWindow", "°C", None))

